language: php

dist: trusty

matrix:
  include:
  - php: 7.1
    env: ANALYSIS='true'
  - php: 7.2
  - php: 7.3
  - php: nightly

  allow_failures:
  - php: nightly

before_script:
- if [[ "$ANALYSIS" == 'true' ]]; then composer require php-coveralls/php-coveralls:^2.1.0 ; fi
- composer install -n

script:
- if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/phpunit --coverage-clover clover.xml ; fi
- if [[ "$ANALYSIS" != 'true' ]]; then vendor/bin/phpunit ; fi
- vendor/bin/phpcs
- vendor/bin/phpstan analyse Slim

after_success:
- if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/php-coveralls --coverage_clover=clover.xml -v ; fi

notifications:
  slack: slimphp:0RNzx2JuhkAqIf0MXcUZ0asT
